import { notFound } from "next/navigation";
import { CollectionNavigation } from "../../../components/CollectionNavigation";
import { EditorialImage } from "../../../components/EditorialImage";
import { JsonLd } from "../../../components/JsonLd";
import { getCollectionNavigation, getPublishedVideoBySlug } from "../../../lib/data/public";
import { canonical, editorialMetadata } from "../../../lib/seo";
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props) { const item = await getPublishedVideoBySlug((await params).slug); return item ? editorialMetadata({ title: item.title, description: item.description, path: `/videos/${item.slug}`, image: item.thumbnail.url, type: "video" }) : { title: "Video | Jyot", robots: { index: false } }; }
export default async function VideoPage({ params }: Props) { const item = await getPublishedVideoBySlug((await params).slug); if (!item) notFound(); const data = { "@context": "https://schema.org", "@type": "VideoObject", name: item.title, description: item.description, thumbnailUrl: item.thumbnail.url, uploadDate: item.publishedAt, url: canonical(`/videos/${item.slug}`), ...(item.videoUrl ? { contentUrl: item.videoUrl } : {}) }; const collectionNavigation = await getCollectionNavigation("video", item.id); return <main className="page-shell section max-w-4xl"><JsonLd data={data} /><p className="eyebrow">{item.category.name}</p><h1 className="serif mt-4 text-5xl md:text-7xl">{item.title}</h1><p className="mt-6 text-lg leading-8 text-[var(--muted)]">{item.description}</p><p className="meta mt-6">{item.author?.name ?? "Jyot"} · {new Date(item.publishedAt).toLocaleDateString("en-US", { dateStyle: "long" })}</p><div className="mt-12"><EditorialImage src={item.thumbnail} alt={item.thumbnail.altText} /></div>{item.videoUrl && <p className="mt-8"><a className="eyebrow border-b border-[var(--orange)] pb-2" href={item.videoUrl}>Watch video →</a></p>}{collectionNavigation[0] && <CollectionNavigation {...collectionNavigation[0]} />}</main>; }
