/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import { DeleteButton } from "../../../components/cms/DeleteButton";
import { deleteContent } from "../../../lib/cms/actions";
import { getAdminVideos as getRawAdminVideos } from "../../../lib/data/admin";
import { mediaDeliveryUrl, mediaSourceFallback } from "../../../lib/media-url";

const filters = [{ value: "", label: "All" }, { value: "draft", label: "Draft" }, { value: "published", label: "Published" }, { value: "scheduled", label: "Scheduled" }];
const formatDate = (value?: Date) => value ? new Date(value).toLocaleDateString("en-IN", { dateStyle: "medium" }) : "—";
const statusLabel = (value: string) => value[0].toUpperCase() + value.slice(1);
const imageUrl = (item: { sourceUrl?: string; objectKey?: string; variants?: { presentation16x9?: { objectKey?: string } } }) => mediaDeliveryUrl(item.variants?.presentation16x9?.objectKey ?? item.objectKey) ?? mediaSourceFallback(item.sourceUrl) ?? "";
const serialize = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const getAdminVideos = async (status?: string) => serialize(await getRawAdminVideos(status));

export default async function AdminVideosPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const status = (await searchParams).status ?? "";
  const items = await getAdminVideos(status);
  return <main><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">CMS</p><h1 className="serif mt-2 text-5xl">Videos</h1></div><a className="bg-[var(--orange)] px-4 py-3 font-bold text-white" href="/admin/videos/new">New video</a></div><nav aria-label="Filter videos" className="mt-8 flex flex-wrap gap-2 border-b pb-4">{filters.map((filter) => <a className={`border px-3 py-2 text-sm ${status === filter.value ? "border-[var(--orange)] text-[var(--orange)]" : ""}`} href={filter.value ? `/admin/videos?status=${filter.value}` : "/admin/videos"} key={filter.value}>{filter.label}</a>)}</nav>{items.length === 0 ? <p className="mt-8 text-[var(--muted)]">No {status || "published or draft"} videos found.</p> : <div className="mt-5 overflow-x-auto border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-[.08em] text-[var(--muted)]"><tr><th className="p-4">Video</th><th className="p-4">Status</th><th className="p-4">Author</th><th className="p-4">Category</th><th className="p-4">Updated</th><th className="p-4">Published</th><th className="p-4">Actions</th></tr></thead><tbody>{items.map((item) => <tr className="border-b last:border-0" key={String(item._id)}><td className="p-4"><div className="flex items-center gap-3">{item.thumbnail && imageUrl(item.thumbnail) && <img className="h-12 w-20 object-cover" src={imageUrl(item.thumbnail)} alt="" />}<a className="font-bold hover:text-[var(--orange)]" href={`/admin/videos/${item._id}/edit`}>{item.title}</a></div></td><td className="p-4"><span className={`admin-status admin-status-${item.status}`}>{statusLabel(item.status)}</span></td><td className="p-4">{item.author?.name ?? "—"}</td><td className="p-4">{item.category?.name ?? "—"}</td><td className="p-4">{formatDate(item.updatedAt)}</td><td className="p-4">{item.status === "scheduled" && item.scheduledAt ? `${formatDate(item.scheduledAt)} scheduled` : formatDate(item.publishedAt)}</td><td className="p-4"><div className="flex gap-3"><a className="text-[var(--orange)]" href={`/admin/videos/${item._id}/edit`}>Edit</a><DeleteButton action={async () => { "use server"; await deleteContent("video", String(item._id)); }} /></div></td></tr>)}</tbody></table></div>}</main>;
}
