import Link from "next/link";
import { getCurrentUser } from "../../../../lib/auth";
import { getDashboardStats } from "../../../../lib/data/admin";

const statusClass: Record<string, string> = { draft: "admin-status admin-status-draft", published: "admin-status admin-status-published", scheduled: "admin-status admin-status-scheduled" };
const date = (value?: Date) => value ? new Date(value).toLocaleDateString("en-IN", { dateStyle: "medium" }) : "—";

export default async function DashboardPage() {
  const [user, stats] = await Promise.all([getCurrentUser(), getDashboardStats()]);
  const cards: [string, number, string][] = [["Published articles", stats.counts.publishedArticles, "Published"], ["Draft articles", stats.counts.draftArticles, "Needs attention"], ["Videos", stats.counts.totalVideos, "All video content"], ["Research", stats.counts.totalResearch, "All research"], ["Collections", stats.counts.totalCollections, "Curated series"], ["Media assets", stats.counts.mediaAssets, "Library total"]];
  const routeFor = (type: string, id: unknown) => `/admin/${type === "Research" ? "research" : `${type.toLowerCase()}s`}/${String(id)}/edit`;
  return <main className="admin-dashboard"><div className="admin-page-heading"><div><p className="admin-kicker">Overview</p><h1 className="admin-page-title">Good morning, {user?.name?.split(" ")[0] ?? "there"}.</h1><p className="admin-page-description">A clear view of what is happening across your publication today.</p></div><div className="admin-quick-actions"><Link href="/admin/articles/new">+ New article</Link><Link href="/admin/videos/new">+ New video</Link><Link href="/admin/research/new">+ New research</Link><Link href="/admin/collections/new">+ New collection</Link></div></div><div className="admin-stat-grid">{cards.map(([label, value, note]) => <div className="admin-stat" key={label}><p className="admin-stat-label">{label}</p><p className="admin-stat-value">{String(value)}</p><p className="admin-stat-note">{note}</p></div>)}</div><section className="admin-recent"><div className="admin-section-heading"><div><p className="admin-kicker">Editorial activity</p><h2>Recently edited</h2></div><Link href="/admin/articles">View all content →</Link></div>{stats.recent.length ? <div className="admin-recent-list">{stats.recent.map((item: { type: string; _id: unknown; title: string; status: string; author?: { name?: string }; updatedAt?: Date }) => <div className="admin-recent-row" key={`${item.type}-${String(item._id)}`}><div><p className="admin-recent-type">{item.type}</p><Link href={routeFor(item.type, item._id)} className="admin-recent-title">{item.title}</Link></div><span className={statusClass[item.status] ?? "admin-status"}>{item.status}</span><span className="admin-recent-author">{item.author?.name ?? "—"}</span><span className="admin-recent-date">{date(item.updatedAt)}</span><Link className="admin-recent-edit" href={routeFor(item.type, item._id)}>Edit</Link></div>)}</div> : <p className="admin-empty">No content has been created yet.</p>}</section></main>;
}
