import Link from "next/link";
import { getCurrentUser } from "../../../../lib/auth";
import { getDashboardStats } from "../../../../lib/data/admin";

const statusClass: Record<string, string> = { draft: "admin-status admin-status-draft", published: "admin-status admin-status-published", scheduled: "admin-status admin-status-scheduled" };
const date = (value?: Date) => value ? new Date(value).toLocaleDateString("en-IN", { dateStyle: "medium" }) : "—";

export default async function DashboardPage() {
  const [user, stats] = await Promise.all([getCurrentUser(), getDashboardStats()]);
  const cards: [string, number][] = [["Total Articles", stats.counts.totalArticles], ["Published Articles", stats.counts.publishedArticles], ["Draft Articles", stats.counts.draftArticles], ["Scheduled Articles", stats.counts.scheduledArticles], ["Total Videos", stats.counts.totalVideos], ["Total Research", stats.counts.totalResearch], ["Media Assets", stats.counts.mediaAssets]];
  const routeFor = (type: string, id: unknown) => `/admin/${type === "Research" ? "research" : `${type.toLowerCase()}s`}/${String(id)}/edit`;
  return <main className="admin-dashboard"><div className="admin-dashboard-heading"><div><p className="eyebrow">CMS Dashboard</p><h1 className="serif mt-2 text-5xl">Welcome, {user?.name}</h1><p className="mt-2 text-[var(--muted)]">Role: {user?.role}</p></div><div className="admin-quick-actions"><Link href="/admin/articles/new">+ New Article</Link><Link href="/admin/videos/new">+ New Video</Link><Link href="/admin/research/new">+ New Research</Link><Link href="/admin/media">Media Library</Link></div></div><div className="admin-stat-grid">{cards.map(([label, value]) => <div className="admin-stat" key={String(label)}><p className="meta">{label}</p><p className="serif admin-stat-value">{String(value)}</p></div>)}</div><section className="admin-recent"><div className="admin-section-heading"><div><p className="eyebrow">Editorial activity</p><h2 className="serif">Recent content</h2></div><Link href="/admin/articles">View articles →</Link></div>{stats.recent.length ? <div className="admin-recent-list">{stats.recent.map((item: { type: string; _id: unknown; title: string; status: string; author?: { name?: string }; updatedAt?: Date }) => <div className="admin-recent-row" key={`${item.type}-${String(item._id)}`}><div><p className="admin-recent-type">{item.type}</p><Link href={routeFor(item.type, item._id)} className="admin-recent-title">{item.title}</Link></div><span className={statusClass[item.status] ?? "admin-status"}>{item.status}</span><span className="admin-recent-author">{item.author?.name ?? "—"}</span><span className="admin-recent-date">{date(item.updatedAt)}</span><Link className="admin-recent-edit" href={routeFor(item.type, item._id)}>Edit</Link></div>)}</div> : <p className="admin-empty">No content has been created yet.</p>}</section></main>;
}
