"use client";
/* eslint-disable @next/next/no-img-element */

import { useRouter } from "next/navigation";
import { useState } from "react";
import { InsertMediaModal, type ArticleMediaPlacement } from "./InsertMediaModal";
import type { MediaPickerAsset } from "./MediaPicker";
import { RichTextEditor } from "./RichTextEditor";
import { TaxonomyMultiSelect } from "./TaxonomyMultiSelect";
import { ResearchTopicPicker } from "./ResearchTopicPicker";
import { EditorialWorkflowActions } from "./EditorialWorkflowActions";
import { mediaUrlForAsset } from "../../lib/media-url";
import { normalizeCmsErrorDetails, validateCmsForm, type CmsFieldErrors } from "../../lib/cms/form-errors";
import { FieldError, FormErrorSummary } from "./FormFeedback";

type Option = { id: string; name: string };
type Props = { action: (formData: FormData) => Promise<unknown>; deleteAction?: (formData: FormData) => Promise<unknown>; kind: "article" | "video" | "research"; value?: Record<string, unknown>; options?: { authors: Option[]; categories: Option[]; tags: Option[] }; defaultStatus?: "draft" | "published" };

export function ContentForm({ action, deleteAction, kind, value = {}, options = { authors: [], categories: [], tags: [] }, defaultStatus }: Props) {
  const router = useRouter();
  const [dirty, setDirty] = useState(false); const [error, setError] = useState(""); const [fieldErrors, setFieldErrors] = useState<CmsFieldErrors>({});
  const [mediaModalOpen, setMediaModalOpen] = useState(false); const [mediaModalSession, setMediaModalSession] = useState(0); const [heroMedia, setHeroMedia] = useState("");
  const articleAuthors = referenceIds(value.author); const articleCategories = referenceIds(value.category); const authors = referenceIds(value.authors);
  const mediaId = (field: string) => String(((value[field] as { _id?: unknown })?._id ?? value[field]) ?? ""); const initialHeroMedia = mediaId("coverMedia"); const heroValue = heroMedia || initialHeroMedia;
  const currentHero = value.coverMedia as { originalName?: string; altText?: string; sourceUrl?: string; objectKey?: string; variants?: { presentation16x9?: { objectKey?: string } } } | undefined;
  const currentHeroUrl = mediaUrlForAsset(currentHero?.variants?.presentation16x9?.objectKey ?? currentHero?.objectKey, currentHero?.sourceUrl);
  const adminPath = kind === "article" ? "/admin/articles" : kind === "video" ? "/admin/videos" : "/admin/research";
  const openHeroMedia = () => { setMediaModalSession((session) => session + 1); setMediaModalOpen(true); };
  const insertMedia = (placement: ArticleMediaPlacement, asset: MediaPickerAsset) => { if (placement === "hero") setHeroMedia(asset._id); setMediaModalOpen(false); setDirty(true); };
  const submit = async (formData: FormData) => { setError(""); try { await action(formData); router.push(adminPath); router.refresh(); } catch (cause) { const details = normalizeCmsErrorDetails(cause, kind, `We couldn't save this ${kind} right now. Please try again.`); setFieldErrors(details.fieldErrors); setError(details.formError); const first = Object.keys(details.fieldErrors)[0]; if (first) { const target = document.querySelector<HTMLElement>(`[name="${first}"]`); target?.scrollIntoView({ behavior: "smooth", block: "center" }); window.setTimeout(() => target?.focus(), 250); } } };
  return <form noValidate action={submit} onSubmit={(event) => { const publishing = String(new FormData(event.currentTarget).get("status") ?? "") === "published" || Boolean(defaultStatus); const result = validateCmsForm(event.currentTarget, kind, publishing); setFieldErrors(result.fieldErrors); if (result.formError) { event.preventDefault(); setError(result.formError); const first = Object.keys(result.fieldErrors)[0]; const target = first ? event.currentTarget.querySelector<HTMLElement>(`[name="${first}"]`) : null; target?.scrollIntoView({ behavior: "smooth", block: "center" }); window.setTimeout(() => target?.focus(), 250); } }} onChange={(event) => { setDirty(true); const field = (event.target as unknown as HTMLInputElement).name; if (field) setFieldErrors((current) => { if (!current[field]) return current; const next = { ...current }; delete next[field]; return next; }); }} className={`max-w-3xl space-y-5 ${kind !== "article" ? "content-form-secondary" : ""}`}>
    <input type="hidden" name="id" value={String(value._id ?? "")} />{defaultStatus && <input type="hidden" name="status" value={defaultStatus} />}
    <FormErrorSummary errors={fieldErrors} formError={error} /><Field label="Title" name="title" value={value.title} required error={fieldErrors.title} /><Field label="Slug" name="slug" value={value.slug} error={fieldErrors.slug} /><p className="-mt-3 text-xs text-[var(--muted)]">Leave blank to generate a URL-safe slug from the title.</p>
    <label className="block text-sm">Summary / excerpt{kind === "article" && <RequiredMark />}<textarea className="mt-1 w-full border p-3" name="excerpt" defaultValue={String(value.excerpt ?? "")} required={kind === "article"} aria-invalid={Boolean(fieldErrors.excerpt)} aria-describedby={fieldErrors.excerpt ? "error-excerpt" : undefined} /><FieldError id="error-excerpt" message={fieldErrors.excerpt} /></label>
    {kind === "research" && <Field label="Description" name="description" value={value.description ?? value.excerpt} required error={fieldErrors.description} textarea />}
    {kind === "article" && <label className="block text-sm cms-editor-section">Body<RequiredMark /><RichTextEditor name="content" initialValue={value.content} onDirty={() => setDirty(true)} /><FieldError message={fieldErrors.content} /></label>}
    {kind === "article" && <><TaxonomyMultiSelect name="author" label="Credited authors" required error={fieldErrors.author} options={options.authors} initialValue={articleAuthors.join(",")} placeholder="Select authors..." /><TaxonomyMultiSelect name="category" label="Category" required error={fieldErrors.category} options={options.categories} initialValue={articleCategories.join(",")} placeholder="Select category..." single /><TaxonomyMultiSelect name="tags" label="Tags" options={options.tags} initialValue={referenceIds(value.tags).join(",")} placeholder="Select tags..." /><section className="cms-article-media-section" aria-labelledby="article-media-heading"><div className="cms-article-media-heading"><div><p className="eyebrow">Media</p><h2 id="article-media-heading" className="serif">Hero image</h2></div><button type="button" className="media-primary-button" onClick={openHeroMedia}>{heroValue ? "Replace hero image" : "Select hero image"}</button></div><input type="hidden" name="coverMedia" value={heroValue} /><FieldError message={fieldErrors.coverMedia} /><div className="cms-article-media-summary"><div><span>{heroValue ? currentHero?.originalName ?? "Existing hero image assigned" : "No hero image selected"}</span><small>Displayed at the top of the published article. Recommended: 16:9, 1600px wide or larger.</small></div></div><p className="cms-article-media-note">This article model has no separate supporting-image field.</p></section><InsertMediaModal key={mediaModalSession} open={mediaModalOpen} onClose={() => setMediaModalOpen(false)} onInsert={insertMedia} allowedPlacements={["hero"]} /></>}
    {kind === "research" && <><section className="cms-article-media-section" aria-labelledby="research-details-heading"><div className="cms-article-media-heading"><div><p className="eyebrow">Research</p><h2 id="research-details-heading" className="serif">Hero image</h2></div><button type="button" className="media-primary-button" onClick={openHeroMedia}>{heroValue ? "Replace hero image" : "Select hero image"}</button></div><input type="hidden" name="coverMedia" value={heroValue} /><div className="cms-article-media-summary"><div>{currentHeroUrl && <img className="mt-3 h-32 w-full max-w-xs object-cover" src={currentHeroUrl} alt={currentHero?.altText ?? currentHero?.originalName ?? "Research hero image"} />}<span>{heroValue ? currentHero?.originalName ?? "Existing hero image assigned" : "No hero image selected"}</span><small>Displayed at the top of the published research. Recommended: 16:9, 1600px wide or larger.</small></div></div></section><section className="cms-editor-section" aria-labelledby="research-body-heading"><h2 id="research-body-heading" className="cms-editor-label">Body<RequiredMark /></h2><RichTextEditor name="content" initialValue={value.content} onDirty={() => setDirty(true)} /><FieldError message={fieldErrors.content} /></section><TaxonomyMultiSelect name="authors" label="Authors" options={options.authors} initialValue={authors.join(",")} placeholder="Select authors..." /><ResearchTopicPicker options={options.categories} value={mediaId("category")} error={fieldErrors.category} /><TaxonomyMultiSelect name="tags" label="Tags" options={options.tags} initialValue={referenceIds(value.tags).join(",")} placeholder="Select tags..." /><Field label="Research type" name="type" value={value.type ?? "Analysis"} required error={fieldErrors.type} /><InsertMediaModal key={mediaModalSession} open={mediaModalOpen} onClose={() => setMediaModalOpen(false)} onInsert={insertMedia} allowedPlacements={["hero"]} /></>}
    {kind === "video" && <><input type="hidden" name="content" value={typeof value.content === "string" ? value.content : value.content ? JSON.stringify(value.content) : ""} /><section className="cms-article-media-section" aria-labelledby="video-content-heading"><div className="cms-article-media-heading"><div><p className="eyebrow">Video</p><h2 id="video-content-heading" className="serif">Video content</h2></div></div><label className="block text-sm">Description<RequiredMark /><RichTextEditor name="description" initialValue={value.description ?? value.excerpt} onDirty={() => setDirty(true)} /></label><Select name="author" label="Presenter / author" value={String(referenceIds(value.author)[0] ?? "")} options={options.authors} /><Select name="category" label="Category" value={mediaId("category")} options={options.categories} required /></section><section className="cms-article-media-section" aria-labelledby="video-source-heading"><div className="cms-article-media-heading"><div><p className="eyebrow">Video</p><h2 id="video-source-heading" className="serif">Video source</h2></div></div><label className="block text-sm">Source type<RequiredMark /><select className="mt-1 w-full border p-3" name="sourceType" defaultValue={String(value.sourceType ?? "external")} required><option value="external">External video</option><option value="r2">R2 media</option></select></label><label className="block text-sm">Provider<select className="mt-1 w-full border p-3" name="provider" defaultValue={String(value.provider ?? "")}><option value="">Select provider</option><option value="youtube">YouTube</option><option value="vimeo">Vimeo</option><option value="other">Other</option></select></label><Field label="Video URL" name="externalUrl" value={value.externalUrl} type="url" /><Field label="Duration" name="duration" value={value.duration} /></section></>}
    {kind !== "article" && <label className="block text-sm">Publication date<input className="mt-1 w-full border p-3" name="publishedAt" type="datetime-local" defaultValue={value.publishedAt ? new Date(String(value.publishedAt)).toISOString().slice(0, 16) : ""} /></label>}
    {dirty && <p className="text-sm text-amber-700">Unsaved changes will be lost if you leave this page.</p>}{error && !Object.keys(fieldErrors).length && <p role="alert" className="cms-form-error">{error}</p>}
    <EditorialWorkflowActions action={action} deleteAction={deleteAction} contentId={String(value._id ?? "")} label={kind} initialStatus={String(value.status ?? "draft")} />
  </form>;
}

function RequiredMark() { return <span aria-hidden="true" className="required-mark">*</span>; }
export function Field({ label, name, value, textarea = false, type = "text", required = false, error }: { label: string; name: string; value: unknown; textarea?: boolean; type?: string; required?: boolean; error?: string }) { const errorId = `error-${name}`; return <label className="block text-sm">{label}{required && <RequiredMark />}{textarea ? <textarea className="mt-1 w-full border p-3" name={name} defaultValue={String(value ?? "")} required={required} aria-invalid={Boolean(error)} aria-describedby={error ? errorId : undefined} /> : <input className="mt-1 w-full border p-3" name={name} type={type} defaultValue={String(value ?? "")} required={required} aria-invalid={Boolean(error)} aria-describedby={error ? errorId : undefined} />}<FieldError id={errorId} message={error} /></label>; }
function Select({ name, label, value, options, required = false, error }: { name: string; label: string; value: string; options: Option[]; required?: boolean; error?: string }) { const [selected, setSelected] = useState(value); const errorId = `error-${name}`; return <label className="block text-sm">{label}{required && <RequiredMark />}<select className="mt-1 w-full border p-3" name={name} value={selected} onChange={(event) => setSelected(event.target.value)} required={required} disabled={!options.length} aria-invalid={Boolean(error)} aria-describedby={error ? errorId : undefined}><option value="">{options.length ? `Select ${label.toLowerCase()}` : `No ${label.toLowerCase()} available. Create one first.`}</option>{options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select>{!options.length && <span className="mt-1 block text-xs text-amber-700">No {label.toLowerCase()} available. Create one first.</span>}<FieldError id={errorId} message={error} /></label>; }
function referenceIds(value: unknown): string[] { const values = Array.isArray(value) ? value : value === undefined || value === null || value === "" ? [] : [value]; return [...new Set(values.map((item) => String((item as { _id?: unknown })?._id ?? item)).filter(Boolean))]; }
