"use client";

import { useRef, useState } from "react";
import { normalizeCmsError, validateCmsForm } from "../../lib/cms/form-errors";

type ContentKind = "video" | "research" | "collection";

export function ContentWorkflowActions({ action, kind }: { action: (formData: FormData) => Promise<unknown>; kind: ContentKind }) {
  const [choice, setChoice] = useState(""); const [pending, setPending] = useState(false); const [feedback, setFeedback] = useState(""); const [error, setError] = useState(""); const formRef = useRef<HTMLFormElement | null>(null); const label = kind[0].toUpperCase() + kind.slice(1);
  const submit = async (status: string) => { if (!formRef.current || pending) return; formRef.current.querySelectorAll<HTMLInputElement | HTMLSelectElement>('[name="status"]').forEach((field) => { field.value = status; }); const validation = validateCmsForm(formRef.current, kind, status !== "draft"); if (Object.keys(validation.fieldErrors).length) { setError(Object.values(validation.fieldErrors).join(" ")); const first = Object.keys(validation.fieldErrors)[0]; const target = formRef.current.querySelector<HTMLElement>(`[name="${first}"]`); target?.scrollIntoView({ behavior: "smooth", block: "center" }); target?.focus(); return; } setError(""); setFeedback(""); setPending(true); try { await action(new FormData(formRef.current)); setFeedback(status === "draft" ? `${label} saved as draft.` : status === "review" ? `${label} submitted for review.` : status === "scheduled" ? "Publishing scheduled." : status === "archived" ? `${label} archived.` : `${label} published successfully.`); setChoice(""); } catch (cause) { setError(normalizeCmsError(cause, `We couldn't complete this ${label.toLowerCase()} action right now. Please try again.`)); } finally { setPending(false); } };
  const choose = (event: React.ChangeEvent<HTMLSelectElement>) => { const next = event.target.value; setChoice(next); setError(""); if (next === "draft") void submit("draft"); if (next === "published") void submit("published"); };
  return <div className="article-workflow-selector"><input ref={(node) => { formRef.current = node?.form ?? null; }} type="hidden" name="status" defaultValue="draft" /><label className="block text-sm font-bold">What do you want to do?<select value={choice} onChange={choose} disabled={pending}><option value="">Select</option><option value="draft">Save Draft</option><option value="review">Submit for Review</option><option value="scheduled">Schedule Publishing</option><option value="published">Publish</option><option value="archived">Archive</option></select></label>{feedback && <p className="mt-3 text-sm text-green-700" role="status">{feedback}</p>}{error && <p className="mt-3 text-sm text-red-700" role="alert">{error}</p>}{choice === "review" && <div className="article-workflow-panel"><h3 className="serif text-2xl">Review {label.toLowerCase()}</h3><p className="mt-2 text-sm">Submit this {label.toLowerCase()} for editorial review.</p><div className="mt-3 flex gap-2"><button type="button" className="border px-3 py-2" disabled={pending} onClick={() => setChoice("")}>Cancel</button><button type="button" className="bg-[var(--orange)] px-3 py-2 font-bold text-white" disabled={pending} onClick={() => void submit("review")}>{pending ? "Submitting…" : "Submit for Review"}</button></div></div>}{choice === "scheduled" && <div className="article-workflow-panel"><h3 className="serif text-2xl">Schedule publishing</h3><label className="mt-3 block text-sm">Publication date<input className="mt-1 w-full border p-3" name="scheduledLocal" type="datetime-local" /></label><input type="hidden" name="scheduledTimezone" value="Asia/Kolkata" /><div className="mt-3 flex gap-2"><button type="button" className="border px-3 py-2" disabled={pending} onClick={() => setChoice("")}>Cancel</button><button type="button" className="bg-[var(--orange)] px-3 py-2 font-bold text-white" disabled={pending} onClick={() => void submit("scheduled")}>{pending ? "Scheduling…" : "Schedule"}</button></div></div>}{choice === "archived" && <div className="article-workflow-panel"><h3 className="serif text-2xl">Archive {label.toLowerCase()}</h3><div className="mt-3 flex gap-2"><button type="button" className="border px-3 py-2" disabled={pending} onClick={() => setChoice("")}>Cancel</button><button type="button" className="bg-[var(--orange)] px-3 py-2 font-bold text-white" disabled={pending} onClick={() => void submit("archived")}>{pending ? "Archiving…" : `Archive ${label}`}</button></div></div>}</div>;
}
