"use client";

import { useEffect, useRef, useState } from "react";
import { normalizeCmsError, validateCmsForm } from "../../lib/cms/form-errors";
import { ConfirmationModal } from "./ConfirmationModal";

type Props = { action: (formData: FormData) => Promise<unknown>; deleteAction?: (formData: FormData) => Promise<unknown>; contentId?: string; label?: string; initialStatus?: string };
type WorkflowChoice = "schedule" | "review" | "archive";

function Icon({ type }: { type: "calendar" | "save" | "trash" | "review" | "archive" }) {
  const paths = { calendar: "M6 2v3M18 2v3M3 9h18M5 4h14a2 2 0 0 1 2 2v13H3V6a2 2 0 0 1 2-2Z", save: "M4 3h13l3 3v15H4V3Zm3 0v6h8V3M7 21v-7h10v7", trash: "M4 7h16M10 11v6M14 11v6M6 7l1 14h10l1-14M9 7V4h6v3", review: "M4 5h16v14H4zM7 9h10M7 13h7", archive: "M4 7h16v13H4zM3 4h18v3H3zM9 12h6" } as const;
  return <svg aria-hidden="true" className="editorial-workflow-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[type]} /></svg>;
}

export function EditorialWorkflowActions({ action, deleteAction, contentId = "", label = "article", initialStatus = "draft" }: Props) {
  const [choice, setChoice] = useState<WorkflowChoice | "">(""); const [menuOpen, setMenuOpen] = useState(false); const [menuPlacement, setMenuPlacement] = useState<"up" | "down">("down"); const [pending, setPending] = useState(false); const [feedback, setFeedback] = useState(""); const [error, setError] = useState(""); const [status, setCurrentStatus] = useState(initialStatus); const [deleteOpen, setDeleteOpen] = useState(false); const formRef = useRef<HTMLFormElement | null>(null); const menuRef = useRef<HTMLDivElement | null>(null); const triggerRef = useRef<HTMLButtonElement | null>(null);
  const name = label[0].toUpperCase() + label.slice(1);
  useEffect(() => { const outside = (event: MouseEvent) => { if (!menuRef.current?.contains(event.target as Node)) setMenuOpen(false); }; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") { setMenuOpen(false); triggerRef.current?.focus(); } }; document.addEventListener("mousedown", outside); document.addEventListener("keydown", escape); return () => { document.removeEventListener("mousedown", outside); document.removeEventListener("keydown", escape); }; }, []);
  useEffect(() => { if (!menuOpen) return; const timer = window.setTimeout(() => { const trigger = triggerRef.current?.getBoundingClientRect(); const menu = menuRef.current?.querySelector<HTMLElement>(".editorial-workflow-menu-list"); if (!trigger || !menu) return; const spaceBelow = window.innerHeight - trigger.bottom; setMenuPlacement(spaceBelow < menu.offsetHeight + 16 && trigger.top > menu.offsetHeight + 16 ? "up" : "down"); }, 0); return () => window.clearTimeout(timer); }, [menuOpen]);
  const setStatus = (next: string) => { setCurrentStatus(next); formRef.current?.querySelectorAll<HTMLInputElement>('[name="status"]').forEach((field) => { field.value = next; }); };
  const submit = async (next: "draft" | "published" | "scheduled" | "review" | "archived") => {
    if (!formRef.current || pending) return;
    const validation = validateCmsForm(formRef.current, label as "article" | "video" | "research", next !== "draft");
    if (Object.keys(validation.fieldErrors).length) { setError(Object.values(validation.fieldErrors).join(" ")); const first = Object.keys(validation.fieldErrors)[0]; const target = formRef.current.querySelector<HTMLElement>(`[name="${first}"]`); target?.scrollIntoView({ behavior: "smooth", block: "center" }); target?.focus(); return; }
    if (next === "scheduled" && !(formRef.current.elements.namedItem("scheduledLocal") as HTMLInputElement | null)?.value) { setError("Scheduled date and time are required."); return; }
    setStatus(next); setPending(true); setMenuOpen(false);
    try { await action(new FormData(formRef.current)); setFeedback(next === "draft" ? `${name} saved as draft.` : next === "scheduled" ? "Publishing scheduled." : next === "review" ? `${name} submitted for review.` : next === "archived" ? `${name} archived.` : `${name} published.`); setChoice(""); } catch (cause) { setError(normalizeCmsError(cause, `We couldn't complete this ${label} action right now. Please try again.`)); } finally { setPending(false); }
  };
  const deleteItem = async () => { if (!deleteAction || !contentId || pending) return; setDeleteOpen(false); setPending(true); setError(""); const data = new FormData(); data.set("id", contentId); try { await deleteAction(data); setFeedback(`${name} deleted.`); } catch (cause) { setError(normalizeCmsError(cause, `We couldn't delete this ${label} right now. Please try again.`)); } finally { setPending(false); } };
  const choose = (next: WorkflowChoice | "draft" | "delete") => { setError(""); setFeedback(""); if (next === "draft") { void submit("draft"); return; } if (next === "delete") { setMenuOpen(false); setDeleteOpen(true); return; } setChoice(next); setMenuOpen(false); };
  return <section className="editorial-workflow-panel" aria-labelledby="editorial-workflow-title"><input ref={(node) => { formRef.current = node?.form ?? null; }} type="hidden" name="status" defaultValue={initialStatus} /><div className="editorial-workflow-header"><div><p className="eyebrow">Publishing</p><h2 id="editorial-workflow-title" className="serif">Publishing</h2></div><span className={`admin-status admin-status-${status}`}><span aria-hidden="true">●</span> {status}</span></div>
    <div className="editorial-workflow-control"><label htmlFor="editorial-workflow-trigger">Action</label><div className="editorial-workflow-menu" ref={menuRef}><div className="editorial-workflow-split"><button type="button" className="editorial-workflow-publish" disabled={pending} onClick={() => void submit("published")}>{pending ? "Publishing..." : "Publish"}</button><button ref={triggerRef} id="editorial-workflow-trigger" type="button" className="editorial-workflow-chevron" aria-label="More publishing actions" aria-haspopup="menu" aria-expanded={menuOpen} disabled={pending} onClick={() => setMenuOpen((open) => !open)}><svg aria-hidden="true" viewBox="0 0 16 16" focusable="false"><path d="m3.5 6 4.5 4 4.5-4" /></svg></button></div>{menuOpen && <div className={`editorial-workflow-menu-list ${menuPlacement === "up" ? "is-up" : ""}`} role="menu"><button type="button" role="menuitem" onClick={() => choose("schedule")}><Icon type="calendar" /><span><strong>Schedule for later</strong><small>Choose a publication date and time.</small></span></button><button type="button" role="menuitem" onClick={() => choose("review")}><Icon type="review" /><span><strong>Submit for review</strong><small>Send this content for editorial review.</small></span></button><button type="button" role="menuitem" onClick={() => choose("archive")}><Icon type="archive" /><span><strong>Archive</strong><small>Remove this content from active content.</small></span></button><button type="button" role="menuitem" onClick={() => choose("draft")}><Icon type="save" /><span><strong>Save draft</strong><small>Keep this content private.</small></span></button>{deleteAction && contentId && <button type="button" role="menuitem" className="editorial-workflow-danger" onClick={() => choose("delete")}><Icon type="trash" /><span><strong>Delete</strong><small>This action cannot be undone.</small></span></button>}</div>}</div></div>
    {choice === "schedule" && <div className="editorial-workflow-schedule"><label>Publication date and time<input name="scheduledLocal" type="datetime-local" /></label><input type="hidden" name="scheduledTimezone" value="Asia/Kolkata" /><p>Times are interpreted in India Standard Time.</p><div className="editorial-workflow-actions"><button type="button" className="media-secondary-button" disabled={pending} onClick={() => setChoice("")}>Cancel</button><button type="button" className="media-primary-button" disabled={pending} onClick={() => void submit("scheduled")}>{pending ? "Scheduling..." : "Schedule"}</button></div></div>}
    {feedback && <p className="editorial-workflow-feedback" role="status">{feedback}</p>}{error && <p className="editorial-workflow-error" role="alert">{error}</p>}<ConfirmationModal open={deleteOpen} title={`Delete ${label}?`} message="This action cannot be undone." confirmLabel="Delete" danger onClose={() => setDeleteOpen(false)} onConfirm={() => void deleteItem()} />
  </section>;
}
