"use client";
/* eslint-disable react-hooks/refs */
import { DndContext, closestCenter, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { useState } from "react";
type Section = { id: string; type: "hero" | "featured" | "articles" | "videos" | "research"; title: string; enabled: boolean; order: number; content: { mode: "manual" | "latest"; ids?: string[]; limit?: number } };
type Props = { initial: { sections: Section[]; revision: number }; candidates: { articles: { id: string; title: string }[]; videos: { id: string; title: string }[]; research: { id: string; title: string }[] }; saveAction: (data: FormData) => Promise<void>; publishAction: (data: FormData) => Promise<void> };
function SortableSection({ section, onChange, candidates }: { section: Section; onChange: (section: Section) => void; candidates: Props["candidates"] }) { const sortable = useSortable({ id: section.id }); const source = section.type === "research" ? candidates.research : section.type === "videos" ? candidates.videos : candidates.articles; const ids = section.content.ids ?? []; return <div ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition }} className="border bg-white p-4"><div className="flex items-center gap-3"><button type="button" className="cursor-grab px-2 text-xl" {...sortable.attributes} {...sortable.listeners}>☷</button><input className="flex-1 border p-2" value={section.title} onChange={(event) => onChange({ ...section, title: event.target.value })} /><label className="text-sm"><input type="checkbox" checked={section.enabled} onChange={(event) => onChange({ ...section, enabled: event.target.checked })} /> Enabled</label></div>{section.type === "articles" || section.type === "videos" ? <label className="mt-4 block text-sm">Latest item limit<input className="ml-3 w-20 border p-2" type="number" min="1" max="12" value={section.content.limit ?? 3} onChange={(event) => onChange({ ...section, content: { mode: "latest", limit: Number(event.target.value) } })} /></label> : <label className="mt-4 block text-sm">Selected content<select className="mt-1 w-full border p-2" multiple value={ids} onChange={(event) => onChange({ ...section, content: { mode: "manual", ids: [...event.target.selectedOptions].map((option) => option.value) } })}>{source.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label>}</div>; }
export function HomepageManager({ initial, candidates, saveAction, publishAction }: Props) { const [sections, setSections] = useState(initial.sections.sort((a, b) => a.order - b.order)); const [revision] = useState(initial.revision); const drag = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; const from = sections.findIndex((item) => item.id === active.id); const to = sections.findIndex((item) => item.id === over.id); const next = [...sections]; const [moved] = next.splice(from, 1); next.splice(to, 0, moved); setSections(next.map((item, index) => ({ ...item, order: index + 1 }))); }; const configuration = JSON.stringify({ revision, sections }); return <><DndContext collisionDetection={closestCenter} onDragEnd={drag}><SortableContext items={sections.map((section) => section.id)} strategy={verticalListSortingStrategy}><div className="space-y-4">{sections.map((section) => <SortableSection key={section.id} section={section} onChange={(next) => setSections((current) => current.map((item) => item.id === next.id ? next : item))} candidates={candidates} />)}</div></SortableContext></DndContext><div className="mt-6 flex gap-3"><form action={saveAction}><input type="hidden" name="configuration" value={configuration} /><button className="bg-[var(--orange)] px-4 py-3 font-bold text-white" type="submit">Save draft</button></form><form action={publishAction}><input type="hidden" name="revision" value={revision} /><button className="border border-[var(--orange)] px-4 py-3 font-bold" type="submit">Publish draft</button></form><a className="border px-4 py-3" href="/admin/homepage/preview">Preview draft</a></div></>; }
