"use client";
/* eslint-disable react-hooks/refs */
import { DndContext, closestCenter, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { useState } from "react";

type BlockType = "hero" | "featured" | "articles" | "videos" | "research" | "research-explorer" | "topic" | "collection";
type Content = { mode: "manual" | "latest"; ids?: string[]; limit?: number; categoryId?: string };
type Section = { id: string; type: BlockType; title: string; enabled: boolean; order: number; content: Content; settings?: { label?: string } };
type Candidate = { id: string; title: string };
type Candidates = { articles: Candidate[]; videos: Candidate[]; research: Candidate[]; collections: Candidate[]; categories: { id: string; name: string }[] };
type Action = (formData: FormData) => Promise<void>;
type Props = { initial: { sections: Section[]; revision: number }; candidates: Candidates; history: { revision: number; createdAt?: string; publishedAt?: string }[]; saveAction: Action; publishAction: Action; discardAction: () => Promise<void>; restoreAction: Action };
const blockNames: Record<BlockType, string> = { hero: "Hero", featured: "Featured", articles: "Latest Insights / Articles", videos: "Videos", research: "Featured Research", "research-explorer": "Research Explorer", topic: "Topic Section", collection: "Collection / Series" };
const sourceFor = (type: BlockType, candidates: Candidates) => type === "videos" ? candidates.videos : type === "research" || type === "research-explorer" ? candidates.research : type === "collection" ? candidates.collections : candidates.articles;
const manualOnly = (type: BlockType) => type === "hero" || type === "featured" || type === "research" || type === "collection";

function SortableSection({ section, candidates, onChange, onMove, onRemove }: { section: Section; candidates: Candidates; onChange: (value: Section) => void; onMove: (direction: -1 | 1) => void; onRemove: () => void }) {
  const sortable = useSortable({ id: section.id }); const source = sourceFor(section.type, candidates); const ids = section.content.ids ?? []; const manual = section.content.mode === "manual";
  const setContent = (content: Content) => onChange({ ...section, content });
  return <article ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition }} className="border border-black/10 bg-white p-4 shadow-sm">
    <div className="flex flex-wrap items-center gap-3"><button type="button" className="cursor-grab px-2 text-xl" aria-label={`Drag ${blockNames[section.type]}`} {...sortable.attributes} {...sortable.listeners}>☷</button><span className="eyebrow">{blockNames[section.type]}</span><span className="text-xs text-black/50">Order {section.order}</span><label className="ml-auto flex items-center gap-2 text-sm"><input type="checkbox" checked={section.enabled} onChange={(event) => onChange({ ...section, enabled: event.target.checked })} /> Enabled</label></div>
    <div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><label className="text-sm">Section title<input className="mt-1 block w-full border p-2" value={section.title} onChange={(event) => onChange({ ...section, title: event.target.value })} /></label><div className="flex items-end gap-2"><button className="border px-3 py-2 text-sm" type="button" onClick={() => onMove(-1)} aria-label="Move section up">↑</button><button className="border px-3 py-2 text-sm" type="button" onClick={() => onMove(1)} aria-label="Move section down">↓</button><button className="border border-red-300 px-3 py-2 text-sm text-red-700" type="button" onClick={onRemove}>Remove</button></div></div>
    {section.type === "collection" && <p className="mt-3 text-sm text-black/60">Select a published collection below. Unpublished collections cannot be added to the homepage.</p>}
    {!manualOnly(section.type) && <div className="mt-4 flex flex-wrap items-end gap-4"><label className="text-sm">Source<select className="mt-1 block border p-2" value={section.content.mode} onChange={(event) => setContent(event.target.value === "manual" ? { mode: "manual", ids: ids.length ? ids : source.slice(0, 1).map((item) => item.id) } : { mode: "latest", limit: section.content.limit ?? 3, categoryId: section.content.categoryId })}><option value="latest">Latest published</option><option value="manual">Selected content</option></select></label>{section.content.mode === "latest" && <label className="text-sm">Limit<input className="mt-1 block w-20 border p-2" type="number" min="1" max="12" value={section.content.limit ?? 3} onChange={(event) => setContent({ ...section.content, mode: "latest", limit: Math.min(12, Math.max(1, Number(event.target.value) || 1)) })} /></label>}{["articles", "videos", "research", "topic", "research-explorer"].includes(section.type) && <label className="text-sm">Topic filter<select className="mt-1 block border p-2" value={section.content.categoryId ?? ""} onChange={(event) => setContent({ ...section.content, categoryId: event.target.value || undefined })}><option value="">All topics</option>{candidates.categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label>}</div>}
    {(manualOnly(section.type) || manual) && <label className="mt-4 block text-sm">Selected {blockNames[section.type]} ({ids.length})<select className="mt-1 block min-h-28 w-full border p-2" multiple value={ids} onChange={(event) => setContent({ ...section.content, mode: "manual", ids: [...event.target.selectedOptions].map((option) => option.value) })}>{source.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label>}
  </article>;
}

export function HomepageManager({ initial, candidates, history, saveAction, publishAction, discardAction, restoreAction }: Props) {
  const [sections, setSections] = useState<Section[]>([...initial.sections].sort((a, b) => a.order - b.order)); const [revision] = useState(initial.revision);
  const update = (next: Section) => setSections((current) => current.map((item) => item.id === next.id ? next : item));
  const move = (id: string, direction: -1 | 1) => setSections((current) => { const index = current.findIndex((item) => item.id === id); const target = index + direction; if (index < 0 || target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next.map((item, order) => ({ ...item, order: order + 1 })); });
  const remove = (id: string) => setSections((current) => current.filter((item) => item.id !== id).map((item, order) => ({ ...item, order: order + 1 })));
  const add = (type: BlockType) => setSections((current) => { const source = sourceFor(type, candidates); const ids = type === "hero" ? source.slice(0, 1).map((item) => item.id) : type === "featured" ? source.slice(0, 3).map((item) => item.id) : type === "collection" ? source.slice(0, 1).map((item) => item.id) : []; return [...current, { id: `custom-${Date.now()}`, type, title: blockNames[type], enabled: true, order: current.length + 1, content: manualOnly(type) ? { mode: "manual" as const, ids } : { mode: "latest" as const, limit: 3 } }]; });
  const drag = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; const from = sections.findIndex((item) => item.id === active.id); const to = sections.findIndex((item) => item.id === over.id); const next = [...sections]; const [moved] = next.splice(from, 1); next.splice(to, 0, moved); setSections(next.map((item, order) => ({ ...item, order: order + 1 }))); };
  const configuration = JSON.stringify({ revision, sections: sections.map((section, order) => ({ ...section, order: order + 1 })) });
  return <div className="mt-8"><div className="mb-6 flex flex-wrap gap-3"><form action={saveAction}><input type="hidden" name="configuration" value={configuration} /><button className="bg-[var(--orange)] px-4 py-3 font-bold text-white" type="submit">Save draft</button></form><form action={publishAction} onSubmit={(event) => { if (!window.confirm(`Publish homepage revision ${revision + 1}? This will replace the currently published homepage configuration.`)) event.preventDefault(); }}><input type="hidden" name="revision" value={revision} /><button className="border border-[var(--orange)] px-4 py-3 font-bold" type="submit">Publish draft</button></form><form action={discardAction}><button className="border px-4 py-3" type="submit">Discard draft changes</button></form><a className="border px-4 py-3" href="/admin/homepage/preview">Preview draft</a></div><h2 className="serif mb-4 text-3xl">Homepage sections</h2><DndContext collisionDetection={closestCenter} onDragEnd={drag}><SortableContext items={sections.map((section) => section.id)} strategy={verticalListSortingStrategy}><div className="space-y-4">{sections.map((section) => <SortableSection key={section.id} section={section} candidates={candidates} onChange={update} onMove={(direction) => move(section.id, direction)} onRemove={() => remove(section.id)} />)}</div></SortableContext></DndContext><div className="mt-5 flex flex-wrap items-center gap-2"><span className="text-sm font-bold">Add section:</span>{(Object.keys(blockNames) as BlockType[]).map((type) => <button className="border px-3 py-2 text-sm" type="button" onClick={() => add(type)} key={type}>{blockNames[type]}</button>)}</div><section className="mt-12 border-t border-black/10 pt-6"><h2 className="serif text-3xl">Revision history</h2>{history.length === 0 ? <p className="mt-3 text-sm text-black/60">Published revisions will appear here after the next publish.</p> : <div className="mt-4 space-y-2">{[...history].reverse().map((item) => <div className="flex flex-wrap items-center gap-3 border-b border-black/10 py-3" key={item.revision}><strong>Revision {item.revision}</strong><span className="text-sm text-black/60">{item.publishedAt ? new Date(item.publishedAt).toLocaleString() : item.createdAt ? new Date(item.createdAt).toLocaleString() : ""}</span><form action={restoreAction} className="ml-auto"><input type="hidden" name="revision" value={item.revision} /><button className="border px-3 py-1 text-sm" type="submit">Restore to draft</button></form></div>)}</div>}</section></div>;
}
