import Link from "next/link";
import { DeleteButton } from "../../../components/cms/DeleteButton";
import { deleteContent } from "../../../lib/cms/actions";
import { getAdminResearch as getRawAdminResearch } from "../../../lib/data/admin";

const displayDate = (item: { status: string; scheduledAt?: Date }) => item.status === "scheduled" && item.scheduledAt ? `Scheduled for ${new Date(item.scheduledAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" })} IST` : "";
const serialize = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const getAdminResearch = async () => serialize(await getRawAdminResearch());
export default async function AdminResearchPage() { const items = await getAdminResearch(); return <main><div className="flex items-center justify-between"><div><p className="eyebrow">CMS</p><h1 className="serif mt-2 text-5xl">Research</h1></div><Link className="bg-[var(--orange)] px-4 py-3 font-bold text-white" href="/admin/research/new">New research</Link></div>{items.length === 0 ? <p className="mt-8 text-[var(--muted)]">No research has been created yet.</p> : <div className="mt-8 overflow-x-auto border bg-white"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-[.08em] text-[var(--muted)]"><tr><th className="p-4">Research</th><th className="p-4">Status</th><th className="p-4">Schedule</th><th className="p-4">Actions</th></tr></thead><tbody>{items.map((item) => <tr className="border-b last:border-0" key={String(item._id)}><td className="p-4"><Link className="font-bold hover:text-[var(--orange)]" href={`/admin/research/${item._id}/edit`}>{item.title}</Link><p className="meta mt-1">/{item.slug}</p></td><td className="p-4"><span className={`admin-status admin-status-${item.status}`}>{item.status}</span></td><td className="p-4 text-[var(--muted)]">{displayDate(item)}</td><td className="p-4"><div className="flex gap-3"><Link className="text-[var(--orange)]" href={`/admin/research/${item._id}/edit`}>Edit</Link><DeleteButton action={async () => { "use server"; await deleteContent("research", String(item._id)); }} /></div></td></tr>)}</tbody></table></div>}</main>; }
