/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { DeleteButton } from "../../../components/cms/DeleteButton";
import { deleteCollection } from "../../../lib/cms/collection-actions";
import { getAdminCollections as getRawAdminCollections } from "../../../lib/data/admin";
import { mediaDeliveryUrl, mediaSourceFallback } from "../../../lib/media-url";

const imageUrl = (item: { sourceUrl?: string; objectKey?: string; variants?: { presentation16x9?: { objectKey?: string } } }) => mediaDeliveryUrl(item.variants?.presentation16x9?.objectKey ?? item.objectKey) ?? mediaSourceFallback(item.sourceUrl) ?? "";
const serialize = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const getAdminCollections = async () => serialize(await getRawAdminCollections());
export default async function AdminCollectionsPage() { const items = await getAdminCollections(); return <main><div className="flex items-center justify-between gap-4"><div><p className="eyebrow">CMS</p><h1 className="serif mt-2 text-5xl">Collections</h1></div><Link className="bg-[var(--orange)] px-4 py-3 font-bold text-white" href="/admin/collections/new">New collection</Link></div>{items.length === 0 ? <p className="mt-8 text-[var(--muted)]">No collections have been created yet.</p> : <div className="mt-8 overflow-x-auto border bg-white"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b text-xs uppercase tracking-[.08em] text-[var(--muted)]"><tr><th className="p-4">Collection</th><th className="p-4">Status</th><th className="p-4">Items</th><th className="p-4">Updated</th><th className="p-4">Published</th><th className="p-4">Actions</th></tr></thead><tbody>{items.map((item) => <tr className="border-b last:border-0" key={String(item._id)}><td className="p-4"><div className="flex items-center gap-3">{item.coverImage && imageUrl(item.coverImage) && <img className="h-12 w-20 object-cover" src={imageUrl(item.coverImage)} alt="" />}<div><Link className="font-bold hover:text-[var(--orange)]" href={`/admin/collections/${item._id}/edit`}>{item.title}</Link><p className="meta mt-1">/{item.slug}</p></div></div></td><td className="p-4"><span className={`admin-status admin-status-${item.status}`}>{item.status}</span></td><td className="p-4">{item.items?.length ?? 0}</td><td className="p-4">{new Date(item.updatedAt).toLocaleDateString("en-IN", { dateStyle: "medium" })}</td><td className="p-4">{item.publishedAt ? new Date(item.publishedAt).toLocaleDateString("en-IN", { dateStyle: "medium" }) : "—"}</td><td className="p-4"><div className="flex gap-3"><Link className="text-[var(--orange)]" href={`/admin/collections/${item._id}/edit`}>Edit</Link><DeleteButton action={async () => { "use server"; await deleteCollection(String(item._id)); }} /></div></td></tr>)}</tbody></table></div>}</main>; }
