"use server";
import { revalidatePath } from "next/cache";
import { Article, Collection, HomepageConfig, Research, Video } from "../db/models";
import { connectToDatabase } from "../db/mongodb";
import { requirePermission } from "../permissions";
import { localDateTimeToUtc, validateFutureSchedule } from "../scheduling";
import { collectionInputSchema } from "../validations/content";

const values = (formData: FormData) => Object.fromEntries([...formData.entries()].map(([key, value]) => [key, typeof value === "string" ? value : ""]));
const ids = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);
const slugify = (value: string) => { const slug = value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 180).replace(/-+$/g, ""); if (!slug) throw new Error("A title is required to generate a slug."); return slug; };
const publicFilter = (contentIds: string[]) => ({ _id: { $in: contentIds }, status: "published", $or: [{ publishedAt: { $exists: false } }, { publishedAt: { $lte: new Date() } }] });
async function verifyItems(items: { type: "article" | "research" | "video"; contentId: string }[]) { const byType = { article: items.filter((item) => item.type === "article").map((item) => item.contentId), research: items.filter((item) => item.type === "research").map((item) => item.contentId), video: items.filter((item) => item.type === "video").map((item) => item.contentId) }; const [articles, research, videos] = await Promise.all([Article.countDocuments(publicFilter(byType.article)), Research.countDocuments(publicFilter(byType.research)), Video.countDocuments(publicFilter(byType.video))]); if (articles !== byType.article.length || research !== byType.research.length || videos !== byType.video.length) throw new Error("Every collection item must be currently published content."); }

export async function saveCollection(formData: FormData) {
  const id = String(formData.get("id") ?? "").trim(); const user = await requirePermission(id ? "collections.edit" : "collections.create"); await connectToDatabase(); const raw = values(formData); const itemTypes = ids(raw.itemTypes); const itemIds = ids(raw.itemIds); if (itemTypes.length !== itemIds.length) throw new Error("Collection items are incomplete. Reload and try again."); const items = itemIds.map((contentId, index) => ({ type: itemTypes[index], contentId, order: index + 1 })); const status = raw.status || "draft"; const scheduledAt = status === "scheduled" ? validateFutureSchedule(localDateTimeToUtc(raw.scheduledLocal, raw.scheduledTimezone || "UTC")) : null; const slug = raw.slug || slugify(raw.title); const duplicate = await Collection.exists({ slug, ...(id ? { _id: { $ne: id } } : {}) }); if (duplicate) throw new Error(`The slug “${slug}” is already in use.`);
  const parsed = collectionInputSchema.safeParse({ title: raw.title, slug, description: raw.description, coverImage: raw.coverImage || undefined, curator: raw.curator || undefined, items, status, scheduledAt, publishedAt: status === "published" ? (raw.publishedAt ? new Date(raw.publishedAt) : new Date()) : undefined, seo: raw.metaTitle || raw.metaDescription ? { metaTitle: raw.metaTitle, metaDescription: raw.metaDescription } : undefined }); if (!parsed.success) throw new Error(`Invalid collection fields: ${parsed.error.issues.map((issue) => issue.message).join(" ")}`); await verifyItems(parsed.data.items); if (status === "published") await requirePermission("collections.publish"); const data = { ...parsed.data, updatedBy: user.id };
  if (id) await Collection.findByIdAndUpdate(id, { $set: data, $unset: status === "published" ? { scheduledAt: "" } : status === "scheduled" ? { publishedAt: "" } : { scheduledAt: "", publishedAt: "" } }, { runValidators: true }); else await Collection.create({ ...data, createdBy: user.id, featured: false });
  revalidatePath("/collections"); revalidatePath(`/collections/${slug}`); revalidatePath("/"); revalidatePath("/admin/collections"); if (id) revalidatePath(`/admin/collections/${id}/edit`); return { ok: true };
}
export async function deleteCollection(id: string) { await requirePermission("collections.delete"); await connectToDatabase(); const used = await HomepageConfig.exists({ $or: [{ "draft.sections.content.ids": id }, { "published.sections.content.ids": id }] }); if (used) throw new Error("Remove this collection from the homepage before deleting it."); await Collection.findByIdAndDelete(id); revalidatePath("/collections"); revalidatePath("/"); revalidatePath("/admin/collections"); }
