"use server";
import { revalidatePath } from "next/cache";
import { connectToDatabase } from "../db/mongodb";
import { Article, HomepageConfig, Research } from "../db/models";
import { requirePermission } from "../permissions";
import { homepageSectionSchema, homepageSnapshotSchema } from "../validations/domain";
import { z } from "zod";
const inputSchema = z.object({ revision: z.number().int().nonnegative(), sections: z.array(homepageSectionSchema) });
function publicFilter(ids: string[]) { return { _id: { $in: ids }, status: "published", $or: [{ publishedAt: { $exists: false } }, { publishedAt: { $lte: new Date() } }] }; }
async function validateReferences(sections: z.infer<typeof homepageSnapshotSchema>["sections"]) { const articleIds = sections.filter((section) => section.type === "hero" || section.type === "featured").flatMap((section) => section.content.ids); const researchIds = sections.filter((section) => section.type === "research").flatMap((section) => section.content.ids); const [articles, research] = await Promise.all([Article.countDocuments(publicFilter(articleIds)), Research.countDocuments(publicFilter(researchIds))]); if (articles !== new Set(articleIds).size || research !== new Set(researchIds).size) throw new Error("Homepage contains unpublished or missing manual content references."); }
export async function saveHomepageDraft(formData: FormData) { const user = await requirePermission("homepage.edit"); const parsed = inputSchema.parse(JSON.parse(String(formData.get("configuration")))); await connectToDatabase(); const config = await HomepageConfig.findOneAndUpdate({ key: "homepage", draftRevision: parsed.revision }, { $set: { draft: { sections: parsed.sections, revision: parsed.revision + 1, updatedAt: new Date() }, draftUpdatedBy: user.id, updatedBy: user.id }, $inc: { draftRevision: 1 } }, { new: true }).lean(); if (!config) throw new Error("Draft changed by another editor. Reload before saving."); revalidatePath("/admin/homepage"); }
export async function publishHomepage(formData: FormData) { const user = await requirePermission("homepage.publish"); const expectedRevision = z.coerce.number().int().nonnegative().parse(formData.get("revision")); await connectToDatabase(); const current = await HomepageConfig.findOne({ key: "homepage", draftRevision: expectedRevision }).lean() as unknown as { draft: { sections: z.infer<typeof homepageSnapshotSchema>["sections"]; revision: number; updatedAt: Date } } | null; if (!current) throw new Error("Draft changed by another editor. Reload before publishing."); const snapshot = homepageSnapshotSchema.parse(current.draft); await validateReferences(snapshot.sections); const published = await HomepageConfig.findOneAndUpdate({ key: "homepage", draftRevision: expectedRevision }, { $set: { published: snapshot, publishedBy: user.id, publishedAt: new Date(), updatedBy: user.id }, $inc: { publishedRevision: 1 } }, { new: true }).lean(); if (!published) throw new Error("Draft changed before publishing. Reload and try again."); revalidatePath("/"); revalidatePath("/articles"); revalidatePath("/videos"); revalidatePath("/research"); revalidatePath("/admin/homepage"); }
