"use server";
import { revalidatePath } from "next/cache";
import sharp from "sharp";
import { connectToDatabase } from "../db/mongodb";
import { Article, HomepageConfig, MediaAsset, Research, Video } from "../db/models";
import { requirePermission } from "../permissions";
import { deleteObjects, getObject, putObject } from "../storage/r2";
import { uploadMediaFile } from "../storage/media";
import { z } from "zod";

export async function uploadMedia(formData: FormData) { const file = formData.get("file"); if (!(file instanceof File)) throw new Error("A file is required."); const focal = { x: Number(formData.get("focalX") ?? 0.5), y: Number(formData.get("focalY") ?? 0.5) }; return uploadMediaFile(file, String(formData.get("altText") ?? ""), focal); }
export async function updateMediaMetadata(formData: FormData) { const user = await requirePermission("media.editMetadata"); const id = String(formData.get("id")); const focalPoint = z.object({ x: z.coerce.number().min(0).max(1), y: z.coerce.number().min(0).max(1) }).parse({ x: formData.get("focalX") ?? 0.5, y: formData.get("focalY") ?? 0.5 }); await connectToDatabase(); const asset = await MediaAsset.findById(id).lean() as unknown as { objectKey: string; variants?: { presentation16x9?: { objectKey: string } }; mimeType: string } | null; if (!asset) throw new Error("Media not found."); const update: Record<string, unknown> = { altText: String(formData.get("altText") ?? ""), caption: String(formData.get("caption") ?? ""), focalPoint, updatedBy: user.id }; if (asset.mimeType.startsWith("image/")) { const original = await getObject(asset.objectKey); const output = await sharp(original).resize({ width: 1600, height: 900, fit: "cover", position: `${Math.round(focalPoint.x * 100)}% ${Math.round(focalPoint.y * 100)}%` }).jpeg({ quality: 86 }).toBuffer(); const variantKey = asset.variants?.presentation16x9?.objectKey ?? `${asset.objectKey}.16x9.jpg`; await putObject(variantKey, output, "image/jpeg"); update["variants.presentation16x9"] = { objectKey: variantKey, width: 1600, height: 900, mimeType: "image/jpeg", size: output.byteLength }; } await MediaAsset.findByIdAndUpdate(id, update, { runValidators: true }); revalidatePath("/admin/media"); revalidatePath("/"); }
export async function deleteMedia(id: string) { await requirePermission("media.delete"); await connectToDatabase(); const [asset, article, video, research, homepage] = await Promise.all([MediaAsset.findById(id).lean() as unknown as Promise<{ objectKey: string; variants?: { presentation16x9?: { objectKey: string } } } | null>, Article.exists({ coverMedia: id }), Video.exists({ $or: [{ thumbnail: id }, { media: id }] }), Research.exists({ $or: [{ coverMedia: id }, { pdfMedia: id }] }), HomepageConfig.exists({ $or: [{ "draft.sections.content.ids": id }, { "published.sections.content.ids": id }] })]); if (!asset) return; if (article || video || research || homepage) throw new Error("Media is still referenced by published or editorial content."); const keys = [asset.objectKey, asset.variants?.presentation16x9?.objectKey ?? ""]; await deleteObjects(keys); await MediaAsset.findByIdAndDelete(id); revalidatePath("/admin/media"); }
